name: nksr
channels:
  - pyg
  - nvidia/label/cuda-12.1.0
  - pytorch
  - conda-forge
  - https://conda.anaconda.org/t/nv-d2214d8d-451e-48fe-8a69-7a2a5ad3b6f5/nvidia
dependencies:
  - python=3.10                   # Fix version for reproducibility
  - pytorch=2.4.0                 # |
  - pytorch-cuda=12.1
  - pytorch-lightning=1.9.4       # |
  - fvdb
  - libprotobuf
  - protobuf
  - mkl
  - numpy<2.0.0
  - tensorboard
  - wandb
  - pybind11
  - pip
  - gitpython
  - ca-certificates
  - certifi
  - openssl
  - cuda-toolkit
  - cuda-cudart
  - cuda-nvcc
  - cuda-tools
  - libcusparse
  - parameterized
  - gcc_linux-64=11
  - gxx_linux-64=11
  - cuda-toolkit
  - setuptools
  - cmake
  - ninja
  - ipython
  - matplotlib
  - tqdm
  - pyg
  - rich
  - pandas
  - pytorch-scatter
  - omegaconf
  - flatten-dict
  - pyntcloud
  - pip:
    - -f https://pycg.huangjh.tech/packages/index.html
    - python-pycg
    - open3d_pycg_cpu
    - open3d
    - randomname
    - pykdtree
    - plyfile
